name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Roda a cada 12 horas
  workflow_dispatch:        # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: fernanda-kailer
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist
          git commit -m "snake: generate new snake animation" || exit 0
          git push
